# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookStore.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62ookStore.proto\x12\x10\x62ookStorePackage\"c\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x02\x12\x0c\n\x04\x64isc\x18\x06 \x01(\x05\"\x14\n\x06\x42ookID\x12\n\n\x02id\x18\x01 \x01(\t\".\n\x05\x42ooks\x12%\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x16.bookStorePackage.Book\"\\\n\nBookWithID\x12(\n\x06\x62ookId\x18\x01 \x01(\x0b\x32\x18.bookStorePackage.BookID\x12$\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x16.bookStorePackage.Book\"\x1f\n\x08Response\x12\x13\n\x0bresponseMsg\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xe9\x02\n\x10\x42ookStoreService\x12\x41\n\x0bGetAllBooks\x12\x17.bookStorePackage.Empty\x1a\x17.bookStorePackage.Books\"\x00\x12\x41\n\x0bGetBookByID\x12\x18.bookStorePackage.BookID\x1a\x16.bookStorePackage.Book\"\x00\x12?\n\x07\x41\x64\x64\x42ook\x12\x16.bookStorePackage.Book\x1a\x1a.bookStorePackage.Response\"\x00\x12H\n\nUpdateBook\x12\x1c.bookStorePackage.BookWithID\x1a\x1a.bookStorePackage.Response\"\x00\x12\x44\n\nDeleteBook\x12\x18.bookStorePackage.BookID\x1a\x1a.bookStorePackage.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bookStore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=37
  _globals['_BOOK']._serialized_end=136
  _globals['_BOOKID']._serialized_start=138
  _globals['_BOOKID']._serialized_end=158
  _globals['_BOOKS']._serialized_start=160
  _globals['_BOOKS']._serialized_end=206
  _globals['_BOOKWITHID']._serialized_start=208
  _globals['_BOOKWITHID']._serialized_end=300
  _globals['_RESPONSE']._serialized_start=302
  _globals['_RESPONSE']._serialized_end=333
  _globals['_EMPTY']._serialized_start=335
  _globals['_EMPTY']._serialized_end=342
  _globals['_BOOKSTORESERVICE']._serialized_start=345
  _globals['_BOOKSTORESERVICE']._serialized_end=706
# @@protoc_insertion_point(module_scope)
