# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bookStore_pb2 as bookStore__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bookStore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class BookStoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllBooks = channel.unary_unary(
                '/bookStorePackage.BookStoreService/GetAllBooks',
                request_serializer=bookStore__pb2.Empty.SerializeToString,
                response_deserializer=bookStore__pb2.Books.FromString,
                _registered_method=True)
        self.GetBookByID = channel.unary_unary(
                '/bookStorePackage.BookStoreService/GetBookByID',
                request_serializer=bookStore__pb2.BookID.SerializeToString,
                response_deserializer=bookStore__pb2.Book.FromString,
                _registered_method=True)
        self.AddBook = channel.unary_unary(
                '/bookStorePackage.BookStoreService/AddBook',
                request_serializer=bookStore__pb2.Book.SerializeToString,
                response_deserializer=bookStore__pb2.Response.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/bookStorePackage.BookStoreService/UpdateBook',
                request_serializer=bookStore__pb2.BookWithID.SerializeToString,
                response_deserializer=bookStore__pb2.Response.FromString,
                _registered_method=True)
        self.DeleteBook = channel.unary_unary(
                '/bookStorePackage.BookStoreService/DeleteBook',
                request_serializer=bookStore__pb2.BookID.SerializeToString,
                response_deserializer=bookStore__pb2.Response.FromString,
                _registered_method=True)


class BookStoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBooks,
                    request_deserializer=bookStore__pb2.Empty.FromString,
                    response_serializer=bookStore__pb2.Books.SerializeToString,
            ),
            'GetBookByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookByID,
                    request_deserializer=bookStore__pb2.BookID.FromString,
                    response_serializer=bookStore__pb2.Book.SerializeToString,
            ),
            'AddBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBook,
                    request_deserializer=bookStore__pb2.Book.FromString,
                    response_serializer=bookStore__pb2.Response.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=bookStore__pb2.BookWithID.FromString,
                    response_serializer=bookStore__pb2.Response.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=bookStore__pb2.BookID.FromString,
                    response_serializer=bookStore__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookStorePackage.BookStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookStoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookStorePackage.BookStoreService/GetAllBooks',
            bookStore__pb2.Empty.SerializeToString,
            bookStore__pb2.Books.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBookByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookStorePackage.BookStoreService/GetBookByID',
            bookStore__pb2.BookID.SerializeToString,
            bookStore__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookStorePackage.BookStoreService/AddBook',
            bookStore__pb2.Book.SerializeToString,
            bookStore__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookStorePackage.BookStoreService/UpdateBook',
            bookStore__pb2.BookWithID.SerializeToString,
            bookStore__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookStorePackage.BookStoreService/DeleteBook',
            bookStore__pb2.BookID.SerializeToString,
            bookStore__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
